# -*- coding: utf-8 -*-
"""hackathon_proj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IKq8p5EJXWYCJvYIICa3nLgIbDhRWTHK
"""

import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

# Importing datasets with the help of csv
file1 = pd.read_csv("air_purifier_293.csv", header = None)

df1 = pd.DataFrame(file1)
#type(int("timestamp"))
df1.head(20)

y = df1.iloc[:, 1].values[1:-1].astype(np.float32)

plt.plot(y)
plt.title("Energy Consumed by Air Purifier")
plt.xlabel('timestamp')
plt.ylabel('Power consumer per hour')
plt.show()

file2 = pd.read_csv('fridge_207.csv', header= None)

df2 = pd.DataFrame(file2)
print(df2)

file3 = pd.read_csv('internet_router_131.csv', header=None)
file4 = pd.read_csv('tv_290.csv', header=None)
file5 = pd.read_csv('washing_machine_157.csv', header=None)
file6 = pd.read_csv('computer_44.csv', header=None)
file7 = pd.read_csv('radiator_309.csv', header=None)

df3 = pd.DataFrame(file3)
df4 = pd.DataFrame(file4)
df5 = pd.DataFrame(file5)
df6 = pd.DataFrame(file6)
df7 = pd.DataFrame(file7)

print(df3)
print(df4)
print(df5)
print(df6)
print(df7)

